### ISSUE TITLE
Error cannot read propery 'match'

### ISSUE THREAD

**Issue by jemershaw** [reedog117/node-vsphere-soap#6]
TypeError: Cannot read property 'match' of undefined
    at _soapErrorHandler (/vsphere/node_modules/node-vsphere-soap/lib/client.js:216:14)
    at /vsphere/node_modules/node-vsphere-soap/lib/client.js:92:9
    at /vsphere/node_modules/soap/lib/client.js:130:7
    at /vsphere/node_modules/soap/lib/client.js:222:7
    at Request._callback (/vsphere/node_modules/soap/lib/http.js:49:7)
    at self.callback (/vsphere/node_modules/request/request.js:198:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/vsphere/node_modules/request/request.js:861:8)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketOnEnd (_http_client.js:300:9)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by patcbuilds** [comment]
Do you have any example code? This is really vague. Also, any particular reason you're using the node-vsphere-soap module and not node-vsphere?

**Comment by jemershaw** [comment]
Actually I think this wasn't an issue with the code. There was a problem on my server and didn't disconnect any sessions. I am using this one just because I coded for this repo. I'll eventually switch but that will take a few months. Why is this repo going to go away?

**Comment by patcbuilds** [comment]
This repo isn't going to go away, but it's designed to be the low-level interface that actually connects to vCenter. My original plan was to have reedog117/node-vsphere be the actual interface that developers use, and hopefully others would submit pull requests to add additional operations beyond the powerOps that are there now.
